### ISSUE TITLE
JPQL - Support subqueries in update statements

### ISSUE THREAD

**Issue by Mobe91** [datanucleus/datanucleus-core#119]
I try to run an update statement like the following:
```
UPDATE Document d SET name = (SELECT MAX(subDoc.name) FROM Document subDoc WHERE subDoc = d)
```
This gives me the following exception and I suspect that subqueries in update statements are just not supported at the moment.
```
java.lang.IllegalArgumentException: JPQL Query contains a keyword ("FROM") that is out of order. Keywords can only be used in a defined order.

	at org.datanucleus.api.jpa.JPAEntityManager.createQuery(JPAEntityManager.java:1488)
	at org.datanucleus.api.jpa.JPAEntityManager.createQuery(JPAEntityManager.java:89)
	at com.blazebit.persistence.impl.AbstractModificationCriteriaBuilder.getQuery(AbstractModificationCriteriaBuilder.java:171)
	at com.blazebit.persistence.impl.AbstractModificationCriteriaBuilder.getQuery(AbstractModificationCriteriaBuilder.java:140)
	at com.blazebit.persistence.criteria.impl.BlazeCriteriaUpdateImpl.getQuery(BlazeCriteriaUpdateImpl.java:98)
	at com.blazebit.persistence.criteria.UpdateTest.setSubquery(UpdateTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.datanucleus.exceptions.NucleusUserException: JPQL Query contains a keyword ("FROM") that is out of order. Keywords can only be used in a defined order.
	at org.datanucleus.query.JPQLSingleStringParser$Compiler.compile(JPQLSingleStringParser.java:122)
	at org.datanucleus.query.JPQLSingleStringParser$Compiler.access$000(JPQLSingleStringParser.java:102)
	at org.datanucleus.query.JPQLSingleStringParser.parse(JPQLSingleStringParser.java:94)
	at org.datanucleus.store.query.AbstractJPQLQuery.<init>(AbstractJPQLQuery.java:110)
	at org.datanucleus.store.rdbms.query.JPQLQuery.<init>(JPQLQuery.java:137)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.datanucleus.plugin.NonManagedPluginRegistry.createExecutableExtension(NonManagedPluginRegistry.java:606)
	at org.datanucleus.plugin.PluginManager.createExecutableExtension(PluginManager.java:330)
	at org.datanucleus.store.query.QueryManagerImpl.newQuery(QueryManagerImpl.java:228)
	at org.datanucleus.api.jpa.JPAEntityManager.createQuery(JPAEntityManager.java:1482)
	... 35 more
```

**Comment by andyjefferson** [comment]
Basic subqueries in UPDATE clause are enabled in v5.0, clearly not part of JPA 2.1
