### ISSUE TITLE
Referring to parent alias in nested subquery leads to an exception

### ISSUE THREAD

**Issue by beikov** [datanucleus/datanucleus-core#173]
When having a query with a nesting level of 2, referring to the outermost alias in the innermost subquery results in an exception. The query looks approximately like this:

```
SELECT d.id FROM Document d WHERE d.id IN (
	SELECT d1.id FROM Document d1 WHERE (
		SELECT COUNT(*) FROM Document d2 WHERE d2.parent.id = d.id
	) > 0
)
```

and the exception I get is

```
Caused by: org.datanucleus.exceptions.NucleusUserException: Variable 'DN_SUBQUERY_1' is unbound and cannot be determined (is it a misspelled field name? or is not intended to be a variable?)
	at org.datanucleus.store.rdbms.query.QueryToSQLMapper.processUnboundExpression(QueryToSQLMapper.java:4615)
	at org.datanucleus.store.rdbms.query.QueryToSQLMapper.processGtExpression(QueryToSQLMapper.java:2717)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compileRelationalExpression(AbstractExpressionEvaluator.java:100)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compileOrAndExpression(AbstractExpressionEvaluator.java:68)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.evaluate(AbstractExpressionEvaluator.java:36)
	at org.datanucleus.query.expression.Expression.evaluate(Expression.java:338)
	at org.datanucleus.query.expression.DyadicExpression.evaluate(DyadicExpression.java:75)
	at org.datanucleus.store.rdbms.query.QueryToSQLMapper.compileFilter(QueryToSQLMapper.java:591)
	at org.datanucleus.store.rdbms.query.QueryToSQLMapper.compile(QueryToSQLMapper.java:464)
	at org.datanucleus.store.rdbms.query.QueryToSQLMapper.processVariableExpression(QueryToSQLMapper.java:4551)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compilePrimaryExpression(AbstractExpressionEvaluator.java:191)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compileUnaryExpression(AbstractExpressionEvaluator.java:172)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compileAdditiveMultiplicativeExpression(AbstractExpressionEvaluator.java:151)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compileRelationalExpression(AbstractExpressionEvaluator.java:126)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.compileOrAndExpression(AbstractExpressionEvaluator.java:68)
	at org.datanucleus.query.expression.AbstractExpressionEvaluator.evaluate(AbstractExpressionEvaluator.java:36)
	at org.datanucleus.query.expression.Expression.evaluate(Expression.java:338)
	at org.datanucleus.query.expression.DyadicExpression.evaluate(DyadicExpression.java:72)
	at org.datanucleus.store.rdbms.query.QueryToSQLMapper.compileFilter(QueryToSQLMapper.java:591)
	at org.datanucleus.store.rdbms.query.QueryToSQLMapper.compile(QueryToSQLMapper.java:464)
	at org.datanucleus.store.rdbms.query.JPQLQuery.compileQueryFull(JPQLQuery.java:833)
	at org.datanucleus.store.rdbms.query.JPQLQuery.compileInternal(JPQLQuery.java:317)
	at org.datanucleus.store.query.Query.executeQuery(Query.java:1883)
	at org.datanucleus.store.query.Query.executeWithMap(Query.java:1829)
	at org.datanucleus.api.jpa.JPAQuery.getResultList(JPAQuery.java:203)
	... 32 more
```

**Comment by beikov** [comment]
[jpa-subquery-nested.zip](https://github.com/datanucleus/datanucleus-core/files/739489/jpa-subquery-nested.zip)

**Comment by andyjefferson** [comment]
Nothing reproduceable with that test on 5.0 or master (5.1) branches, so assumed fixed by previous changes somewhere. Not tried on 4.x but then that branch is effectively closed now

**Comment by beikov** [comment]
What do you mean by 5.0? The current state of the branch or 5.0.6? Because 5.0.6 fails as the test shows.

**Comment by andyjefferson** [comment]
I meant GitHub branch "5.0" and GitHub branch "master". Not had a release for over a month on 5.0 and not any on 5.1 yet

**Comment by beikov** [comment]
Ah just tried the snapshot and it works properly. Thanks!
