### ISSUE TITLE
Ridiculously complicated query can lead to StackOverflowError

### ISSUE THREAD

**Issue by BELUGABEHR** [datanucleus/datanucleus-core#299]
java.lang.StackOverflowError
at org.datanucleus.query.expression.ExpressionCompiler.compileOrAndExpression(ExpressionCompiler.java:192)
at org.datanucleus.query.expression.ExpressionCompiler.compileExpression(ExpressionCompiler.java:179)
at org.datanucleus.query.expression.ExpressionCompiler.compileOrAndExpression(ExpressionCompiler.java:192)
at org.datanucleus.query.expression.ExpressionCompiler.compileExpression(ExpressionCompiler.java:179)
at org.datanucleus.query.expression.ExpressionCompiler.compileOrAndExpression(ExpressionCompiler.java:192)
at org.datanucleus.query.expression.ExpressionCompiler.compileExpression(ExpressionCompiler.java:179)
at org.datanucleus.query.expression.ExpressionCompiler.compileOrAndExpression(ExpressionCompiler.java:192)
at org.datanucleus.query.expression.ExpressionCompiler.compileExpression(ExpressionCompiler.java:179)
at org.datanucleus.query.expression.ExpressionCompiler.compileOrAndExpression(ExpressionCompiler.java:192)
at org.datanucleus.query.expression.ExpressionCompiler.compileExpression(ExpressionCompiler.java:179)

When a statement with many OR predicates is submitted, a StackOverflowError ensues.

**Comment by BELUGABEHR** [comment]
Or allow for some sort of configurable maximum number and produce an Exception with a helpful error message.

**Comment by andyjefferson** [comment]
If that is a problem to you then you get the code and develop something. In 8+ years of using the current generic query compilation my queries don't have a problem of that nature.

**Comment by andyjefferson** [comment]
No reproduceable testcase provided, and no apparent willingness to contribute anything so closing. If anybody comes up with such a situation and is willing to work on it then this can be reopened to cover it. Thx
