### ISSUE TITLE
Support for Java 11 bytecode?

### ISSUE THREAD

**Issue by ludoch** [datanucleus/datanucleus-core#314]
With configuring a project with open jdk 11, I get this error:

Exception in thread "main" java.lang.UnsupportedOperationException
	at org.datanucleus.enhancer.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:244)
	at org.datanucleus.enhancer.asm.ClassReader.accept(ClassReader.java:651)
	at org.datanucleus.enhancer.asm.ClassReader.accept(ClassReader.java:391)
	at org.datanucleus.enhancer.ClassEnhancerImpl.getClassNameForFileName(ClassEnhancerImpl.java:451)
	at org.datanucleus.enhancer.DataNucleusEnhancer.getFileMetadataForInput(DataNucleusEnhancer.java:712)
	at org.datanucleus.enhancer.DataNucleusEnhancer.enhance(DataNucleusEnhancer.java:501)
	at org.datanucleus.enhancer.DataNucleusEnhancer.main(DataNucleusEnhancer.java:1157)

Maybe an upgrade to ASM 7.0 is necessary?

**Comment by chrisco484** [comment]
We've got corporate clients whose current standard for deployments is Java 8 (with some legacy products still in Java 7).
I think it will be many years before they even think of moving to Java 11 but I do understand the desire to use the latest Java has on offer.

**Comment by andyjefferson** [comment]
This project has been open source since day one (not that the majority of people know what that really means). Consequently you can contribute pull requests for such features if they are important to you (this is not important to me personally). For those people unwilling to contribute then [they can pay for such features to be provided](http://datanucleus.org/support.html#commercial).  Very simple

**Comment by ludoch** [comment]
"WIll ASM 7.0 generate .class files that are compatible with older Java versions?"
Yes, this is the intent. You can check which JVM target you need, and configure ASM to generate bytecode for the given platform, so ASM7.0 would cover latest and previous versions, via some code checks.
I'll see if I can get more code samples, and pending free time, happy to contribute.
