### ISSUE TITLE
Closing `PersistenceManager` can cause deadlocks when `datanucleus.multithreaded=true`

### ISSUE THREAD

**Issue by nscuro** [datanucleus/datanucleus-core#479]
## Bug Report

First off, I am very much aware that usage of multithreaded PMs is not recommended. However, for the time being I'm stuck with it and flicking it to non-multithreaded is not an option right now.

What I'm seeing is that certain interactions with multithreaded PMs can cause deadlocks, despite one instance not being used by multiple threads. In my case, many threads create and close their own PMs (but other areas of the application may still use PMs in multiple threads, which is why I can't disable that feature). One of the interactions that trigger this behavior is closing the PM.

With the following test, I'm able to somewhat reliably trigger deadlocks with DN 6.x:

```java
public class MultithreadTest {

    @Test
    public void testMulti() throws InterruptedException, ExecutionException {
        final PersistenceManagerFactory pmf = JDOHelper.getPersistenceManagerFactory("MyTest");

        final ExecutorService es = Executors.newFixedThreadPool(40);

        final List<TestCallable> tasks = new ArrayList<>();
        for (int i = 0; i < 10000; i++) {
            tasks.add(new TestCallable(pmf));
        }

        final List<Future<Void>> futures = es.invokeAll(tasks);
        for (Future<Void> future : futures) {
            future.get();
        }
    }

    private static class TestCallable implements Callable<Void> {

        private final PersistenceManagerFactory pmf;

        TestCallable(final PersistenceManagerFactory pmf) {
            this.pmf = pmf;
        }

        @Override
        public Void call() {
            final PersistenceManager pm = pmf.getPersistenceManager();
            pm.close();
            return null;
        }
    }
```

When running into a deadlock, a thread dump reveals stack traces like the following:

```
"pool-2-thread-16" #34 prio=5 os_prio=31 cpu=8.38ms elapsed=35.33s tid=0x0000000156091c00 nid=0x8003 waiting on condition  [0x0000000174cba000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@17.0.4/Native Method)
	- parking to wait for  <0x000000060183b040> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@17.0.4/LockSupport.java:211)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.4/AbstractQueuedSynchronizer.java:715)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@17.0.4/AbstractQueuedSynchronizer.java:938)
	at java.util.concurrent.locks.ReentrantLock$Sync.lock(java.base@17.0.4/ReentrantLock.java:153)
	at java.util.concurrent.locks.ReentrantLock.lock(java.base@17.0.4/ReentrantLock.java:322)
	at org.datanucleus.ExecutionContextThreadedImpl.threadLock(ExecutionContextThreadedImpl.java:68)
	- locked <0x0000000601800410> (a org.datanucleus.ExecutionContextThreadedImpl)
	at org.datanucleus.ExecutionContextThreadedImpl.close(ExecutionContextThreadedImpl.java:180)
	at org.datanucleus.api.jdo.JDOPersistenceManager.internalClose(JDOPersistenceManager.java:179)
	at org.datanucleus.api.jdo.JDOPersistenceManager.close(JDOPersistenceManager.java:154)
	at org.datanucleus.test.MultithreadTest$TestCallable.call(MultithreadTest.java:48)
	at org.datanucleus.test.MultithreadTest$TestCallable.call(MultithreadTest.java:37)
	at java.util.concurrent.FutureTask.run(java.base@17.0.4/FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@17.0.4/ThreadPoolExecutor.java:1136)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@17.0.4/ThreadPoolExecutor.java:635)
	at java.lang.Thread.run(java.base@17.0.4/Thread.java:833)
```

I am not seeing this behavior with DN 5.2.x. Could this be a regression introduced by https://github.com/datanucleus/datanucleus-core/issues/434?

**Comment by nscuro** [comment]
Test setup in a fork of test-jdo is here: https://github.com/nscuro/datanucleus-test-jdo/tree/issue-479

The test may need to be run multiple times to trigger the deadlock.

**Comment by andyjefferson** [comment]
No interest from me. The factory pattern is clean, so I see no reason to use a single PM across multiple threads. 

The question for DN development really should be, why don't we rip out all code that attempts to cater for the million and one use-cases that this "feature" introduces ? (particularly as DN only ever cater for a handful of them, and does nothing at all around SCO container usage under multiple threads). Which other persistence provider provides thread safe PM / EM / Session ? All this locking has a cost

**Comment by andyjefferson** [comment]
Making sure that the ECPool checkIn is done right at the end of EC.close means this doesn't appear for me. And no, it is nothing to do with #434 which is for StateManager, and you have none.
