### ISSUE TITLE
ClassUtilsTest test failures on JDK 21

### ISSUE THREAD

**Issue by cushon** [datanucleus/datanucleus-core#491]
`ClassUtilsTest.testGetSuperinterfaces` and `ClassUtilsTest.testGetSuperinterfacesDiamond` fail on JDK 21.

The JDK collection interfaces changed as part of [JEP 431: Sequenced Collections](https://openjdk.org/jeps/431).

Repro:

```
$ mvn -version
Apache Maven 3.8.7
Maven home: /usr/share/maven
Java version: 21-ea
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", arch: "amd64", family: "unix"

$ mvn package
...
[ERROR] testGetSuperinterfacesDiamond(org.datanucleus.util.ClassUtilsTest)  Time elapsed: 0.006 s  <<< FAILURE!
junit.framework.AssertionFailedError: ListSet should have had 4 superinterfaces, but had 5
        at org.datanucleus.util.ClassUtilsTest.testGetSuperinterfacesDiamond(ClassUtilsTest.java:196)

[ERROR] testGetSuperinterfaces(org.datanucleus.util.ClassUtilsTest)  Time elapsed: 0 s  <<< FAILURE!
junit.framework.AssertionFailedError: java.util.ArrayList should have had 6 superinterfaces, but had 7
        at org.datanucleus.util.ClassUtilsTest.testGetSuperinterfaces(ClassUtilsTest.java:172)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   ClassUtilsTest.testGetSuperinterfaces:172 java.util.ArrayList should have had 6 superinterfaces, but had 7
[ERROR]   ClassUtilsTest.testGetSuperinterfacesDiamond:196 ListSet should have had 4 superinterfaces, but had 5
```

**Comment by andyjefferson** [comment]
Since Java 21 is not yet "released" (and certainly not available to me), and not supported, then that is not a surprise

**Comment by cushon** [comment]
Early access builds are available, e.g. [here](https://jdk.java.net/21/) and [here](https://www.azul.com/downloads/?version=java-21-ea&package=jdk#zulu)
